-- R&B MAISON — production notification system
-- Notifications are created only from committed backend events. Clients cannot insert.

CREATE TYPE public.notification_type AS ENUM (
  'merchant_application',
  'merchant_approved',
  'merchant_rejected',
  'new_order',
  'order_payment_required',
  'order_paid',
  'shipping_confirmed',
  'delivery_completed',
  'profit_released',
  'deposit_pending',
  'deposit_approved',
  'deposit_rejected',
  'withdrawal_pending',
  'withdrawal_approved',
  'withdrawal_rejected',
  'admin_action'
);

CREATE TYPE public.notification_read_status AS ENUM ('unread', 'read');

CREATE TABLE public.notifications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  type public.notification_type NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  data jsonb NOT NULL DEFAULT '{}'::jsonb,
  read_status public.notification_read_status NOT NULL DEFAULT 'unread',
  created_at timestamptz NOT NULL DEFAULT now(),
  read_at timestamptz,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT notifications_title_chk CHECK (char_length(btrim(title)) BETWEEN 1 AND 120),
  CONSTRAINT notifications_message_chk CHECK (char_length(btrim(message)) BETWEEN 1 AND 500),
  CONSTRAINT notifications_data_chk CHECK (jsonb_typeof(data) = 'object'),
  CONSTRAINT notifications_read_at_chk CHECK (
    (read_status = 'unread' AND read_at IS NULL)
    OR (read_status = 'read' AND read_at IS NOT NULL)
  )
);

CREATE INDEX idx_notifications_user_created
  ON public.notifications (user_id, created_at DESC);
CREATE INDEX idx_notifications_user_unread
  ON public.notifications (user_id)
  WHERE read_status = 'unread';
CREATE INDEX idx_notifications_type ON public.notifications (type);

COMMENT ON TABLE public.notifications IS
  'In-app notifications generated by backend events. Clients cannot create or edit content.';

CREATE TRIGGER trg_notifications_set_updated_at
  BEFORE UPDATE ON public.notifications
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Mutation guards
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.protect_notification_columns()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'Notifications cannot be deleted';
  END IF;

  IF NEW.user_id IS DISTINCT FROM OLD.user_id
     OR NEW.type IS DISTINCT FROM OLD.type
     OR NEW.title IS DISTINCT FROM OLD.title
     OR NEW.message IS DISTINCT FROM OLD.message
     OR NEW.data IS DISTINCT FROM OLD.data
     OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
    RAISE EXCEPTION 'Notification content cannot be changed';
  END IF;

  IF NEW.read_status IS DISTINCT FROM OLD.read_status
     AND NOT (
       OLD.read_status = 'unread'
       AND NEW.read_status = 'read'
     ) THEN
    RAISE EXCEPTION 'Notifications can only be marked read';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_notifications_protect
  BEFORE UPDATE OR DELETE ON public.notifications
  FOR EACH ROW
  EXECUTE FUNCTION public.protect_notification_columns();

-- ---------------------------------------------------------------------------
-- RLS — no client inserts
-- ---------------------------------------------------------------------------

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications REPLICA IDENTITY FULL;

CREATE POLICY notifications_select_own
  ON public.notifications
  FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());

CREATE POLICY notifications_update_own_read
  ON public.notifications
  FOR UPDATE
  TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- ---------------------------------------------------------------------------
-- Writers (SECURITY DEFINER / service_role only)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.create_notification(
  p_user_id uuid,
  p_type public.notification_type,
  p_title text,
  p_message text,
  p_data jsonb DEFAULT '{}'::jsonb
)
RETURNS public.notifications
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_row public.notifications;
BEGIN
  IF p_user_id IS NULL THEN
    RAISE EXCEPTION 'Notification user is required';
  END IF;

  INSERT INTO public.notifications (
    user_id,
    type,
    title,
    message,
    data
  )
  VALUES (
    p_user_id,
    p_type,
    btrim(p_title),
    btrim(p_message),
    COALESCE(p_data, '{}'::jsonb)
  )
  RETURNING * INTO v_row;

  RETURN v_row;
END;
$$;

CREATE OR REPLACE FUNCTION public.notify_admins(
  p_type public.notification_type,
  p_title text,
  p_message text,
  p_data jsonb DEFAULT '{}'::jsonb
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_admin record;
  v_count integer := 0;
BEGIN
  FOR v_admin IN
    SELECT p.user_id
    FROM public.profiles p
    WHERE p.role = 'admin'
      AND p.status = 'active'
  LOOP
    PERFORM public.create_notification(
      v_admin.user_id,
      p_type,
      p_title,
      p_message,
      p_data
    );
    v_count := v_count + 1;
  END LOOP;

  RETURN v_count;
END;
$$;

CREATE OR REPLACE FUNCTION public.order_notification_payload(p_order_id uuid)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT jsonb_build_object(
    'order_id', o.id,
    'store_id', o.store_id,
    'store', s.store_name,
    'merchant_id', o.merchant_id,
    'amount', o.total_amount,
    'currency', o.currency,
    'product', coalesce(
      (
        SELECT string_agg(pr.name, ', ' ORDER BY oi.created_at)
        FROM public.order_items oi
        JOIN public.products pr ON pr.id = oi.product_id
        WHERE oi.order_id = o.id
      ),
      ''
    )
  )
  FROM public.orders o
  LEFT JOIN public.stores s ON s.id = o.store_id
  WHERE o.id = p_order_id;
$$;

CREATE OR REPLACE FUNCTION public.merchant_user_id(p_merchant_id uuid)
RETURNS uuid
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT m.user_id
  FROM public.merchants m
  WHERE m.id = p_merchant_id;
$$;

-- ---------------------------------------------------------------------------
-- Event triggers
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.notify_merchant_application_event()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF TG_OP = 'INSERT' AND NEW.status = 'pending' THEN
    PERFORM public.create_notification(
      NEW.user_id,
      'merchant_application',
      'Application Submitted',
      'Your store application has been submitted and is waiting for review.',
      jsonb_build_object(
        'application_id', NEW.id,
        'store_name', NEW.store_name
      )
    );
    PERFORM public.notify_admins(
      'merchant_application',
      'New Merchant Application',
      'A customer submitted a store application.',
      jsonb_build_object(
        'application_id', NEW.id,
        'store_name', NEW.store_name,
        'user_id', NEW.user_id
      )
    );
  ELSIF TG_OP = 'UPDATE' AND OLD.status IS DISTINCT FROM NEW.status THEN
    IF NEW.status = 'approved' THEN
      PERFORM public.create_notification(
        NEW.user_id,
        'merchant_approved',
        'Store Approved',
        'Your store has been approved. Merchant access is now available.',
        jsonb_build_object(
          'application_id', NEW.id,
          'store_id', NEW.store_id,
          'merchant_id', NEW.merchant_id,
          'unlocked', jsonb_build_array(
            'Shop Details',
            'Wholesale',
            'Products',
            'Store Orders',
            'Wallet'
          )
        )
      );
    ELSIF NEW.status = 'rejected' THEN
      PERFORM public.create_notification(
        NEW.user_id,
        'merchant_rejected',
        'Store Application Rejected',
        'Your store application was rejected.',
        jsonb_build_object(
          'application_id', NEW.id,
          'reason', NEW.rejection_reason
        )
      );
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_merchant_applications_notify
  AFTER INSERT OR UPDATE OF status ON public.merchant_applications
  FOR EACH ROW
  EXECUTE FUNCTION public.notify_merchant_application_event();

CREATE OR REPLACE FUNCTION public.notify_merchant_verification_event()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF OLD.verification_status IS DISTINCT FROM NEW.verification_status THEN
    IF NEW.verification_status = 'approved' THEN
      PERFORM public.create_notification(
        NEW.user_id,
        'merchant_approved',
        'Store Approved',
        'Your store has been approved. Merchant access is now available.',
        jsonb_build_object(
          'merchant_id', NEW.id,
          'store_id', NEW.store_id,
          'unlocked', jsonb_build_array(
            'Shop Details',
            'Wholesale',
            'Products',
            'Store Orders',
            'Wallet'
          )
        )
      );
    ELSIF NEW.verification_status = 'rejected' THEN
      PERFORM public.create_notification(
        NEW.user_id,
        'merchant_rejected',
        'Store Application Rejected',
        'Your store application was rejected.',
        jsonb_build_object(
          'merchant_id', NEW.id
        )
      );
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_merchants_notify_verification
  AFTER UPDATE OF verification_status ON public.merchants
  FOR EACH ROW
  WHEN (OLD.verification_status IS DISTINCT FROM NEW.verification_status)
  EXECUTE FUNCTION public.notify_merchant_verification_event();

CREATE OR REPLACE FUNCTION public.notify_new_order_event()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_payload jsonb;
  v_user_id uuid;
BEGIN
  v_user_id := public.merchant_user_id(NEW.merchant_id);
  IF v_user_id IS NULL THEN
    RETURN NEW;
  END IF;

  v_payload := public.order_notification_payload(NEW.id);

  PERFORM public.create_notification(
    v_user_id,
    'new_order',
    'New Order',
    'You have received a new store order.',
    v_payload
  );

  RETURN NEW;
END;
$$;

CREATE CONSTRAINT TRIGGER trg_orders_notify_new
  AFTER INSERT ON public.orders
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW
  EXECUTE FUNCTION public.notify_new_order_event();

CREATE OR REPLACE FUNCTION public.notify_order_status_event()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_payload jsonb;
  v_user_id uuid;
BEGIN
  IF OLD.status IS NOT DISTINCT FROM NEW.status THEN
    RETURN NEW;
  END IF;

  v_user_id := public.merchant_user_id(NEW.merchant_id);
  v_payload := public.order_notification_payload(NEW.id);

  IF NEW.status = 'paid' THEN
    PERFORM public.create_notification(
      v_user_id,
      'order_paid',
      'Order Paid',
      'Wholesale payment for the order succeeded.',
      v_payload
    );
  ELSIF NEW.status = 'shipping' THEN
    PERFORM public.notify_admins(
      'shipping_confirmed',
      'Order Ready For Delivery Confirmation',
      'Merchant has confirmed shipping.',
      v_payload
    );
  ELSIF NEW.status = 'delivered' THEN
    PERFORM public.create_notification(
      v_user_id,
      'delivery_completed',
      'Order Completed',
      'Customer received the product.',
      v_payload
    );
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_orders_notify_status
  AFTER UPDATE OF status ON public.orders
  FOR EACH ROW
  EXECUTE FUNCTION public.notify_order_status_event();

CREATE OR REPLACE FUNCTION public.notify_profit_release_event()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id uuid;
BEGIN
  IF NEW.type <> 'profit_release' OR NEW.status <> 'completed' THEN
    RETURN NEW;
  END IF;

  SELECT m.user_id INTO v_user_id
  FROM public.wallets w
  JOIN public.merchants m ON m.id = w.merchant_id
  WHERE w.id = NEW.wallet_id;

  IF v_user_id IS NULL THEN
    RETURN NEW;
  END IF;

  PERFORM public.create_notification(
    v_user_id,
    'profit_released',
    'Profit Released',
    'Your order profit has been released.',
    jsonb_build_object(
      'amount', NEW.amount,
      'currency', NEW.currency,
      'order_id', NEW.reference_id,
      'transaction_id', NEW.id
    )
  );

  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_wallet_transactions_notify_profit
  AFTER INSERT ON public.wallet_transactions
  FOR EACH ROW
  WHEN (NEW.type = 'profit_release' AND NEW.status = 'completed')
  EXECUTE FUNCTION public.notify_profit_release_event();

CREATE OR REPLACE FUNCTION public.notify_deposit_request_event()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id uuid;
  v_payload jsonb;
BEGIN
  v_user_id := public.merchant_user_id(NEW.merchant_id);
  v_payload := jsonb_build_object(
    'request_id', NEW.id,
    'amount', NEW.amount,
    'asset', NEW.asset,
    'network', NEW.network
  );

  IF TG_OP = 'INSERT' AND NEW.status = 'pending' THEN
    PERFORM public.create_notification(
      v_user_id,
      'deposit_pending',
      'Deposit Pending',
      'Your deposit request is waiting for admin review.',
      v_payload
    );
    PERFORM public.notify_admins(
      'deposit_pending',
      'New Deposit Request',
      'A merchant submitted a deposit request.',
      v_payload || jsonb_build_object('merchant_id', NEW.merchant_id)
    );
  ELSIF TG_OP = 'UPDATE' AND OLD.status IS DISTINCT FROM NEW.status THEN
    IF NEW.status = 'approved' THEN
      PERFORM public.create_notification(
        v_user_id,
        'deposit_approved',
        'Deposit Approved',
        'Your deposit has been approved.',
        v_payload
      );
    ELSIF NEW.status = 'rejected' THEN
      PERFORM public.create_notification(
        v_user_id,
        'deposit_rejected',
        'Deposit Rejected',
        'Your deposit request was rejected.',
        v_payload
      );
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_deposit_requests_notify
  AFTER INSERT OR UPDATE OF status ON public.wallet_deposit_requests
  FOR EACH ROW
  EXECUTE FUNCTION public.notify_deposit_request_event();

CREATE OR REPLACE FUNCTION public.notify_withdrawal_request_event()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id uuid;
  v_payload jsonb;
BEGIN
  v_user_id := public.merchant_user_id(NEW.merchant_id);
  v_payload := jsonb_build_object(
    'request_id', NEW.id,
    'amount', NEW.amount,
    'asset', NEW.asset,
    'network', NEW.network
  );

  IF TG_OP = 'INSERT' AND NEW.status = 'pending' THEN
    PERFORM public.create_notification(
      v_user_id,
      'withdrawal_pending',
      'Withdrawal Pending',
      'Your withdrawal request is waiting for admin review.',
      v_payload
    );
    PERFORM public.notify_admins(
      'withdrawal_pending',
      'New Withdrawal Request',
      'A merchant submitted a withdrawal request.',
      v_payload || jsonb_build_object('merchant_id', NEW.merchant_id)
    );
  ELSIF TG_OP = 'UPDATE' AND OLD.status IS DISTINCT FROM NEW.status THEN
    IF NEW.status = 'approved' THEN
      PERFORM public.create_notification(
        v_user_id,
        'withdrawal_approved',
        'Withdrawal Approved',
        'Your withdrawal has been approved.',
        v_payload
      );
    ELSIF NEW.status = 'rejected' THEN
      PERFORM public.create_notification(
        v_user_id,
        'withdrawal_rejected',
        'Withdrawal Rejected',
        'Your withdrawal request was rejected.',
        v_payload
      );
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_withdrawal_requests_notify
  AFTER INSERT OR UPDATE OF status ON public.withdrawal_requests
  FOR EACH ROW
  EXECUTE FUNCTION public.notify_withdrawal_request_event();

CREATE OR REPLACE FUNCTION public.notify_admin_action_event()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id uuid;
  v_title text;
  v_message text;
BEGIN
  IF NEW.action IN ('approve_merchant', 'reject_merchant') THEN
    RETURN NEW;
  END IF;

  v_title := 'Admin Action';
  v_message := coalesce(NEW.description, 'An administrator updated your account.');

  IF NEW.action IN ('suspend_user', 'restore_user') AND NEW.target_type = 'profiles' THEN
    SELECT p.user_id INTO v_user_id FROM public.profiles p WHERE p.id = NEW.target_id;
    v_title := CASE WHEN NEW.action = 'suspend_user' THEN 'Account Suspended' ELSE 'Account Restored' END;
  ELSIF NEW.action IN ('add_funds', 'remove_funds') AND NEW.target_type = 'wallets' THEN
    SELECT m.user_id INTO v_user_id
    FROM public.wallets w
    JOIN public.merchants m ON m.id = w.merchant_id
    WHERE w.id = NEW.target_id;
    v_title := 'Wallet Balance Updated';
  ELSIF NEW.action = 'adjust_credit_score' THEN
    SELECT m.user_id INTO v_user_id
    FROM public.merchant_credit_scores cs
    JOIN public.merchants m ON m.id = cs.merchant_id
    WHERE cs.id = NEW.target_id;
    v_title := 'Credit Score Updated';
  ELSIF NEW.action IN ('suspend_store', 'approve_store') AND NEW.target_type = 'stores' THEN
    SELECT m.user_id INTO v_user_id
    FROM public.stores s
    JOIN public.merchants m ON m.id = s.merchant_id
    WHERE s.id = NEW.target_id;
    v_title := CASE WHEN NEW.action = 'suspend_store' THEN 'Store Suspended' ELSE 'Store Activated' END;
  ELSIF NEW.action IN ('enable_wholesale_access', 'suspend_wholesale_access') THEN
    SELECT m.user_id INTO v_user_id FROM public.merchants m WHERE m.id = NEW.target_id;
    v_title := 'Wholesale Access Updated';
  ELSE
    RETURN NEW;
  END IF;

  IF v_user_id IS NULL OR v_user_id = NEW.admin_id THEN
    RETURN NEW;
  END IF;

  PERFORM public.create_notification(
    v_user_id,
    'admin_action',
    v_title,
    v_message,
    jsonb_build_object(
      'action', NEW.action,
      'target_type', NEW.target_type,
      'target_id', NEW.target_id,
      'log_id', NEW.id
    )
  );

  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_admin_activity_logs_notify
  AFTER INSERT ON public.admin_activity_logs
  FOR EACH ROW
  EXECUTE FUNCTION public.notify_admin_action_event();

-- ---------------------------------------------------------------------------
-- Payment-required (persisted outside the rolled-back confirm transaction)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.notify_order_payment_required(p_order_id uuid)
RETURNS public.notifications
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_order public.orders;
  v_user_id uuid;
  v_payload jsonb;
  v_row public.notifications;
BEGIN
  SELECT * INTO v_order
  FROM public.orders
  WHERE id = p_order_id;

  IF v_order.id IS NULL THEN
    RAISE EXCEPTION 'Order not found';
  END IF;

  v_user_id := public.merchant_user_id(v_order.merchant_id);
  v_payload := public.order_notification_payload(v_order.id);

  v_row := public.create_notification(
    v_user_id,
    'order_payment_required',
    'Payment Required',
    'Wholesale payment failed. Please top up your account.',
    v_payload
  );

  PERFORM public.notify_admins(
    'admin_action',
    'Suspicious Activity',
    'A merchant order payment failed due to insufficient wholesale balance.',
    v_payload || jsonb_build_object('reason', 'insufficient_wholesale_balance')
  );

  RETURN v_row;
END;
$$;

-- ---------------------------------------------------------------------------
-- Reader / mark-read APIs
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.my_notifications()
RETURNS SETOF public.notifications
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public
AS $$
  SELECT *
  FROM public.notifications
  WHERE user_id = auth.uid()
  ORDER BY
    CASE WHEN read_status = 'unread' THEN 0 ELSE 1 END,
    created_at DESC;
$$;

CREATE OR REPLACE FUNCTION public.notification_unread_count()
RETURNS bigint
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public
AS $$
  SELECT count(*)
  FROM public.notifications
  WHERE user_id = auth.uid()
    AND read_status = 'unread';
$$;

CREATE OR REPLACE FUNCTION public.mark_notification_read(p_id uuid)
RETURNS public.notifications
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_row public.notifications;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Authentication required';
  END IF;

  UPDATE public.notifications
  SET read_status = 'read',
      read_at = coalesce(read_at, now())
  WHERE id = p_id
    AND user_id = auth.uid()
  RETURNING * INTO v_row;

  IF v_row.id IS NULL THEN
    RAISE EXCEPTION 'Notification not found';
  END IF;

  RETURN v_row;
END;
$$;

CREATE OR REPLACE FUNCTION public.mark_all_notifications_read()
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_count integer;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Authentication required';
  END IF;

  UPDATE public.notifications
  SET read_status = 'read',
      read_at = coalesce(read_at, now())
  WHERE user_id = auth.uid()
    AND read_status = 'unread';

  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
$$;

-- Realtime: clients subscribe to postgres_changes on this table for their user_id.
DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.notifications;
EXCEPTION
  WHEN duplicate_object THEN
    NULL;
  WHEN undefined_object THEN
    NULL;
END
$$;

REVOKE ALL ON FUNCTION public.create_notification(uuid, public.notification_type, text, text, jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.notify_admins(public.notification_type, text, text, jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.order_notification_payload(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.merchant_user_id(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.notify_order_payment_required(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.my_notifications() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.notification_unread_count() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.mark_notification_read(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.mark_all_notifications_read() FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.create_notification(uuid, public.notification_type, text, text, jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.notify_admins(public.notification_type, text, text, jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.order_notification_payload(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.merchant_user_id(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.notify_order_payment_required(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.my_notifications() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.notification_unread_count() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.mark_notification_read(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.mark_all_notifications_read() TO authenticated, service_role;
